<a href="https://colab.research.google.com/github/ashik7555-netizen/Python-Basics-Case-Study/blob/main/numpy_class_activity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [1]:
import numpy as np

arr = np.arange(10, 50)
matrix = arr.reshape(4, 10)
last_col = matrix[:, -1]

print("Reshaped Matrix:\n", matrix)
print("Last Column:", last_col)

Reshaped Matrix:
 [[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
Last Column: [19 29 39 49]

In [2]:
m1 = np.full((3,3),5)
m2 = np.arange(1,10).reshape(3,3)
added = m1 + m2
multiplied = m1 + m2
transposed = multiplied.T
print("Transposed Result:\n", transposed)

Transposed Result:
 [[ 6  9 12]
 [ 7 10 13]
 [ 8 11 14]]

In [3]:
np.random.seed(42)
rand_arr = np.random.randint(10, 101, 15)
print("Original:", rand_arr)

mask = rand_arr > 50
replaced_count = np.sum(mask)
rand_arr[mask] = -1

print("Modified:", rand_arr)
print("Number of replaced values:", replaced_count)

Original: [61 24 81 70 30 92 96 84 84 97 33 12 31 62 11]
Modified: [-1 24 -1 -1 30 -1 -1 -1 -1 -1 33 12 31 -1 11]
Number of replaced values: 9

In [4]:
np.random.seed(42)
float_arr = np.random.rand(5, 4)
row_sums = np.sum(float_arr, axis=1)
max_sum_row_idx = np.argmax(row_sums)
print("Row index with max sum:", max_sum_row_idx)
row_mins = float_arr.min(axis=1, keepdims=True)
row_maxs = float_arr.max(axis=1, keepdims=True)
normalized_arr = (float_arr - row_mins) / (row_maxs - row_mins)

print("Normalized Array:\n", np.round(normalized_arr, 2))

Row index with max sum: 0
Normalized Array:
 [[0.   1.   0.62 0.39]
 [0.12 0.12 0.   1.  ]
 [0.61 0.72 0.   1.  ]
 [1.   0.05 0.   0.  ]
 [0.06 1.   0.6  0.  ]]

In [5]:
arr5 = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
unique_elements, counts = np.unique(arr5, return_counts=True)
duplicates = unique_elements[counts > 1]

print("Unique elements:", unique_elements)
print("Duplicates:", duplicates)

Unique elements: [1 3 5 7 9]
Duplicates: [1 3 5]

In [6]:
arr6 = np.arange(1, 37).reshape(6, 6)
submatrix = arr6[1:5, 1:5]
evens = submatrix[submatrix % 2 == 0]

print("Middle Submatrix:\n", submatrix)
print("Even numbers:", evens)

Middle Submatrix:
 [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]
Even numbers: [ 8 10 14 16 20 22 26 28]

In [7]:
arr7 = np.arange(12).reshape(3, 4)
reshaped_2x6 = arr7.reshape(2, 6)
flattened = reshaped_2x6.flatten()
final_shape = flattened.reshape(4, 3)

print("Final 4x3 Array:\n", final_shape)

Final 4x3 Array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

In [8]:
a = np.array([[1, 2], [3, 4]])
a = np.append(a, [[5, 6]], axis=0)
col_to_append = np.array([[7], [8], [9]])
a = np.append(a, col_to_append, axis=1)

print("Final Appended Array:\n", a)

Final Appended Array:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
joined = np.concatenate((a, b, c))
matrix3x3 = joined.reshape(3, 3)
diagonal = np.diagonal(matrix3x3)

print("3x3 Matrix:\n", matrix3x3)
print("Diagonal Elements:", diagonal)

3x3 Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Diagonal Elements: [1 5 9]

In [10]:
arr10 = np.arange(1,21)
divisible_vals =arr10[(arr10 % 3 == 0) | (arr10 % 5 == 0)]
count_divisible = len(divisible_vals)
print("Divisible Values:", divisible_vals)
print("Count of Divisible Values:", count_divisible)

Divisible Values: [ 3  5  6  9 10 12 15 18 20]
Count of Divisible Values: 9

Pandas

In [12]:
import numpy as np
import pandas as pd
df = pd.read_csv('/content/titanic_dataset (1).csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [13]:
("\n--- Q2: Missing values per column ---")
df
(df.isnull().sum())
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [14]:
print("\n--- Q3: Survival percentage by gender ---")
survival_by_gender = df.groupby('Sex')['Survived'].mean() * 100
print(survival_by_gender)

--- Q3: Survival percentage by gender ---
Sex
female    74.203822
male      18.890815
Name: Survived, dtype: float64

In [15]:
print("\n--- Q4: Age Statistics (Average, Median, Std Dev) ---")
age_stats = df['Age'].agg(['mean', 'median', 'std'])
print(age_stats)

--- Q4: Age Statistics (Average, Median, Std Dev) ---
mean      29.699118
median    28.000000
std       14.526497
Name: Age, dtype: float64

In [16]:
print("\n--- Q5: Passenger count by class ---")
class_counts = df['Pclass'].value_counts().sort_index()
print(class_counts)

--- Q5: Passenger count by class ---
Pclass
1    216
2    184
3    491
Name: count, dtype: int64

In [17]:
("\n--- Q6: Female, under 18, and survived ---")
df
young_female_survivors = df[(df['Sex'] == 'female') & (df['Age'] < 18) & (df['Survived'] == 1)]
(young_female_survivors)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [18]:
print("\n--- Q7: Replacing missing ages with median ---")
median_age = df['Age'].median()
df['Age'] = df['Age'].fillna(median_age)
print(f"Missing 'Age' values after replacement: {df['Age'].isnull().sum()}")

--- Q7: Replacing missing ages with median ---
Missing 'Age' values after replacement: 0

In [19]:
print("\n--- Q8: Creating age_group column ---")
def categorize_age(age):
    if age < 18:
        return 'Child'
    elif age <= 60:
        return 'Adult'
    else:
        return 'Senior'

df['age_group'] = df['Age'].apply(categorize_age)
print(df[['Age', 'age_group']].head())

--- Q8: Creating age_group column ---
    Age age_group
0  22.0     Adult
1  38.0     Adult
2  26.0     Adult
3  35.0     Adult
4  35.0     Adult

In [20]:
print("\n--- Q9: Top 5 highest fares ---")
top_fares = df.nlargest(5, 'Fare')
print(top_fares[['Name', 'Fare']])

--- Q9: Top 5 highest fares ---
                                   Name      Fare
258                    Ward, Miss. Anna  512.3292
679  Cardeza, Mr. Thomas Drake Martinez  512.3292
737              Lesurer, Mr. Gustave J  512.3292
27       Fortune, Mr. Charles Alexander  263.0000
88           Fortune, Miss. Mabel Helen  263.0000

In [21]:
print("\n--- Q10: Average fare by class and sex ---")
avg_fare_grouped = df.groupby(['Pclass', 'Sex'])['Fare'].mean()
print(avg_fare_grouped)

--- Q10: Average fare by class and sex ---
Pclass  Sex
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: Fare, dtype: float64

In [22]:
print("\n--- Q11: Renaming columns ---")
df = df.rename(columns={'Sex': 'gender', 'Fare': 'ticket_fare'})
print("Current columns:", df.columns.tolist())

--- Q11: Renaming columns ---
Current columns: ['PassengerId', 'Survived', 'Pclass', 'Name', 'gender', 'Age', 'SibSp', 'Parch', 'Ticket', 'ticket_fare', 'Cabin', 'Embarked', 'age_group']

In [23]:
print("\n--- Q12: Survival counts by class ---")
survival_counts_by_class = df.groupby(['Pclass', 'Survived']).size()
print(survival_counts_by_class)

--- Q12: Survival counts by class ---
Pclass  Survived
1       0            80
        1           136
2       0            97
        1            87
3       0           372
        1           119
dtype: int64

In [24]:
import pandas as pd
if 'gender' not in df.columns:
    df = df.rename(columns={'Sex': 'gender'})

print("\n--- Q13: Average age by class and gender ---")
avg_age_grouped = df.groupby(['Pclass', 'gender'])['Age'].mean()
print(avg_age_grouped)

--- Q13: Average age by class and gender ---
Pclass  gender
1       female    33.978723
        male      38.995246
2       female    28.703947
        male      30.512315
3       female    23.572917
        male      26.911873
Name: Age, dtype: float64